### ISSUE TITLE
Permission denied (publickey,keyboard-interactive)

### ISSUE THREAD

**Issue by AndreaCallia** [linuxserver/docker-openssh-server#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
I expect it makes me start an interactive SSH session with the specified username, after asking for a password.

## Current Behavior
It says:
```Permission denied (publickey,keyboard-interactive)```

## Steps to Reproduce

1. Create the docker image (see below for details)
2. Start the server with ```docker start openssh-server```
3. Connect to the server with ```ssh -l andrea -p 2222 localhost```

## Environment
**OS:** MacOS     
**CPU architecture:** x86_64  
**How docker service was installed:**      

```brew cask install docker```

## Command used to create docker container (run/create/compose/screenshot)

```
docker create   --name=openssh-server   \ 
-e PUID=501   -e PGID=20  \
-e TZ=Europe/London  \
-e USER_PASSWORD=andrea  \
-e USER_NAME=andrea \
-p 2222:2222 \
--restart unless-stopped
```

**Comment by aptalca** [comment]
You also need `PASWORD_ACCESS=true` because by default, only key based access is allowed

**Comment by AndreaCallia** [comment]
Many thanks @aptalca ... I tried to add:
```-e PASWORD_ACCESS=true```
to the `docker create` command (of course after `docker stop` and `docker rm`), but when connecting with `ssh -l andrea -p 2222 localhost` it still says:
```Permission denied (publickey,keyboard-interactive)```

**Comment by aptalca** [comment]
Looks like I had a typo, there should be two `S`'s in password, sorry about that.

So it would be `-e PASSWORD_ACCESS=true`

**Comment by AndreaCallia** [comment]
It worked :) as you can see in my previous message there was a typo, I wrote "PASWORD" instead of "PASSWORD". Many thanks for your suggestion... it would be good to add the instructions about adding `-e PASWORD_ACCESS=true` on the usage instructions.

**Comment by aptalca** [comment]
It is already in there 😉

**Comment by AndreaCallia** [comment]
ooops it was there you are right, sorry, my mistake, and thanks again for your support 😊
