### ISSUE TITLE
Feature Req: add fail2ban or other methods for preventing brute-force

### ISSUE THREAD

**Issue by firefly2442** [linuxserver/docker-openssh-server#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

Feature request: [Fail2ban](https://github.com/fail2ban/fail2ban) or alternatives might be helpful in preventing brute-force attack attempts.

**Comment by aptalca** [comment]
@anoma
perhaps a candidate for https://github.com/linuxserver/docker-fail2ban

**Comment by trallnag** [comment]
I would also argue that a dedicated fail2ban container is preferable, as the IP will likely be the same anyway

**Comment by drizuid** [comment]
will not be added to this container but may be added to the referenced above project.
