### ISSUE TITLE
What's the best practice for PUBLIC_KEY_FILE

### ISSUE THREAD

**Issue by ddhp** [linuxserver/docker-openssh-server#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
specified `PUBLIC_KEY_FILE` should be added to `/config/.ssh/authorized_keys` in the container

## Current Behavior
it won't be added since the file only exists in the host machine, or did I miss something?

## Steps to Reproduce
1. `docker create --name=openssh-server -e PUBLIC_KEY_FILE=path/to/host/pub/key linuxserver/openssh-server && docker start openssh-server`
2. `docker exec openssh-server cat /config/.ssh/authorized_keys`

## Environment
**OS:**      OSX
**CPU architecture:** x86_64
**How docker service was installed:** Docker Desktop on Mac

## Command used to create docker container (run/create/compose/screenshot)
as above

## Docker logs
```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing... 
User name is set to linuxserver.io
Sudo is disabled.
User/password ssh access is disabled.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by aptalca** [comment]
The path you define for the key file has to be a path inside the container, not on host

**Comment by ddhp** [comment]
Right, I think how to put the pubic key into the container is not in the scope of this docker image, and thanks for providing this flag.
I will figure out what's the best practice
Thanks for your reply!

**Comment by aptalca** [comment]
Docker secrets is one way, which is mentioned in the readme. Alternatively you can just volume map it anywhere and put in the container address into that env var

**Comment by ddhp** [comment]
Right!

Can I ask unrelated followup question?
I found out the home folder(ie `~`) of the created user is `/config`. Is this expected and if so what's the idea behind the implementation? 
Thanks in advance!
