### ISSUE TITLE
Feature req: Add option for badusernames

### ISSUE THREAD

**Issue by akoscomp** [linuxserver/docker-openssh-server#21]
I want to use long username with uppercase characters for container and I got an error now.
useradd with --badnames option works fine.
I don't found where you create user, if you help me, I can try to create a pull request.

**Comment by aptalca** [comment]
Useradd is done in the baseimage dockerfile. This image only changes the user/group name: https://github.com/linuxserver/docker-openssh-server/blob/master/root/etc/cont-init.d/10-adduser#L8-L10

**Comment by akoscomp** [comment]
I made a pull request for this issue:
https://github.com/linuxserver/docker-openssh-server/pull/23
