### ISSUE TITLE
-e UMASK doesn't apply to sftp transfers

### ISSUE THREAD

**Issue by grantemsley** [linuxserver/docker-openssh-server#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When using, -e UMASK=0002, files transfered via sftp should have that umask applied.

## Current Behavior

umask for transfered files remains 0022

## Steps to Reproduce
1. Transfer a file via sftp
2. Look at file permissions

This can be fixed by changing the line 
<code>
Subsystem sftp /usr/lib/ssh/sftp-server'
</code>
to
<code>
Subsystem sftp /usr/lib/ssh/sftp-server -u <UMASK>
</code>

https://serverfault.com/questions/70876/how-to-put-desired-umask-with-sftp

## Environment
**OS:** unRaid 6.8.3
**CPU architecture:** x86_64
**How docker service was installed:** unRaid

**Comment by aptalca** [comment]
@grantemsley can you give this test image a try?
`lspipepr/openssh-server:8.3_p1-r0-pkg-7bf0505c-pr-25`
Just replace `linuxserver/openssh-server` with that and recreate the container.
We'll merge the PR once you confirm it works, then you can switch back to the main image.

**Comment by grantemsley** [comment]
Yes, that works perfectly. The umask specified in the docker environment gets set for sftp now, and files get created with the expected permissions. Thanks!
