### ISSUE TITLE
Question about user/password activation

### ISSUE THREAD

**Issue by zepouet** [linuxserver/docker-openssh-server#32]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

To be able to connect with a couple of user/password even if we know it is not the best way to do it.

## Current Behavior

We run the container with the minimum of options and we add user directly into with unix command.

## Steps to Reproduce

1. Run the container
```
docker run -d  \
      --name=openssh-server \
      --hostname=openssh-server  \
       -e PUID=1000  \
       -e PGID=1000   \
       -e TZ=Europe/London -e SUDO_ACCESS=false  \
       -e PASSWORD_ACCESS=true   \
       -e USER_PASSWORD=password \
       -e USER_NAME=linuxserver.io  \
       -p 2222:2222  \
       --restart unless-stopped  \
ghcr.io/linuxserver/openssh-server
```
2. Add user into container

```
docker exec -it openssh-server useradd -m johndoe -pchangeit
```

3. Connect via ssh into the container

```
ssh -p 2222 johdnoe@localhost
```

4. Never way to connect

```
johndoe@localhost's password:
Permission denied, please try again.
````

## Environment
**OS: CentOS 7

```
[root@centos-s-2vcpu-4gb-fra1-01 ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:42 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:19:17 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by aptalca** [comment]
This image is not meant for multiple users. Run a separate instance for each user.

**Comment by zepouet** [comment]
ok @aptalca thanks a lot for your response. 

Is it a problem link to rootless usage of the process ? 
For my understanding, it is because the sshd processus is non root and cannot read /etc/password or /etc/shadow.

Thanks

**Comment by aptalca** [comment]
/etc/passwd has group and other read permissions so likely not.

But in any case, we don't support multiple users in this image for various other reasons (sshd running as the user being just one of them)

**Comment by zepouet** [comment]
Thanks @aptalca 

Finally my request is maybe impossible... 
Maybe using sshd without root cannot be possible for multiple users.
If it is possible technically I could try to do it except if it silly to do it and you will never use it.
You have the only one image rootless about this process. 

https://security.stackexchange.com/questions/180471/what-are-the-disadvantages-of-running-ssh-daemon-without-root

Best regards,
Nicolas

**Comment by aptalca** [comment]
Like I said, this image was designed from the ground up for a single user. For multiple users, use multiple containers (I have 3 on my home server currently). I mean, this is all about isolation and sandboxing, so you probably want to customize all vars and volumes for different users and sandbox them from each other anyway.
