### ISSUE TITLE
Readme markdown formatting error

### ISSUE THREAD

**Issue by jhollowe** [linuxserver/docker-openssh-server#39]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

In the ["Application Setup"](https://github.com/linuxserver/docker-openssh-server#application-setup) section, there is incorrect formatting for the markdown inline code sections. An apostrophe (') is used instead of a backtick (\`) around `PUBLIC_KEY_DIR` ([affected lines](https://github.com/linuxserver/docker-openssh-server/blob/master/readme-vars.yml#L59-L60))

This error is visible in the GitHub repo and in the description of the container in container registries (e.g. Docker Hub).

**Comment by jhollowe** [comment]
I can create a PR if it would be helpful, but the documentation said to not create PRs for README contents.

**Comment by jhollowe** [comment]
@aptalca any possibility of getting this fixed?

**Comment by aptalca** [comment]
It was already fixed a while back

**Comment by jhollowe** [comment]
sweet, thanks!
