### ISSUE TITLE
Enable Logging, memory issue

### ISSUE THREAD

**Issue by AquaMCU** [linuxserver/docker-openssh-server#47]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I try to enable logging. As described, I have enabled logging in sshd_config
SyslogFacility AUTH
LogLevel INFO

and try to follow the logfiles with:
sudo docker-compose logs --follow openssh

I expect the information when someone logs into the server to be shown on the console

## Current Behavior

No information after startup in logfiles

## Steps to Reproduce

See above

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64/arm32/arm64 I686
**How docker service was installed:** apt-get install docker-compose

**Comment by aptalca** [comment]
logs are in the config folder

**Comment by AquaMCU** [comment]
Hey, perfect!
