### ISSUE TITLE
Feature Request: Google Authenticator/TOTP Support

### ISSUE THREAD

**Issue by kbrierly** [linuxserver/docker-openssh-server#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I Currently use a self made docker container based on ubuntu 20.04 and google authenticator pam module for my ssh access.
 
This docker container would be a perfect replacement if it had support for google authenticator pam module for ssh and importing of the auth secret from a file or command line. Not sure if it could be done via a plugin.

Pam module github: https://github.com/google/google-authenticator-libpam

## Current Behavior

No additional auth prompts(MFA)
## Alternatives Considered

None tried as of now, suggestions welcome for 2FA/MFA alternatives that do not require a centralized server.

**Comment by drizuid** [comment]
I would suggest seeing if you can create a docker mod to accomplish this: 
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by kbrierly** [comment]
A Docker mod would allow for the installation of the package, but far as i can tell would not provide a way to import A totp token.

**Comment by thespad** [comment]
You should be able to install [the module](https://pkgs.alpinelinux.org/package/v3.15/community/x86_64/google-authenticator) and then you can exec into the container and run the setup to generate the QR code/key for TOTP auth.

**Comment by kbrierly** [comment]
i think i've properly created a docker mod on github for this, but never done this before.

https://github.com/kbrierly/docker-mods/tree/google-authenticator

**Comment by drizuid** [comment]
> i think i've properly created a docker mod on github for this, but never done this before.

did you perform any testing after using your mod?

**Comment by kbrierly** [comment]
> > i think i've properly created a docker mod on github for this, but never done this before.
> 
> did you perform any testing after using your mod?

not  as of yet. haven't had the time to come back to this.
