### ISSUE TITLE
Providing static host keys prevents ssh server startup

### ISSUE THREAD

**Issue by Archelyst** [linuxserver/docker-openssh-server#57]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
I want the SSH server to have host keys that do not change when it restarts. This is especially important since I'm running it in a swarm, so it can get moved to a different node any time, which changes the host keys. Hence, I mount SSH keys like so:

```
# docker-compose.yml
# ...
    configs:
      - source: hostkey
        target: /config/ssh_host_keys/ssh_host_ecdsa_key
        mode: 0600
        uid: "1000"
        gid: "1000"
      - source: hostkeypub
        target: /config/ssh_host_keys/ssh_host_ecdsa_key.pub
        mode: 0644
        uid: "1000"
        gid: "1000"
      - source: hostkey_ed25519
        target: /config/ssh_host_keys/ssh_host_ed25519_key
        mode: 0600
        uid: "1000"
        gid: "1000"
      - source: hostkeypub_ed25519
        target: /config/ssh_host_keys/ssh_host_ed25519_key.pub
        mode: 0644
        uid: "1000"
        gid: "1000"
      - source: hostkey_rsa
        target: /config/ssh_host_keys/ssh_host_rsa_key
        mode: 0600
        uid: "1000"
        gid: "1000"
      - source: hostkeypub_rsa
        target: /config/ssh_host_keys/ssh_host_rsa_key.pub
        mode: 0644
        uid: "1000"
        gid: "1000"
```

## Current Behavior
Unfortunately, when I do this, the openssh server tells me `sshd: no hostkeys available -- exiting.`

Interestingly, when I omit either of the three key pairs, it works. Then, however, the third pair gets regenerated and causes hostkey checks to fail.

## Environment
**OS:** Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:** Official repo

## Command used to create docker container (run/create/compose/screenshot)
`docker swarm deploy`

## Docker logs

> [cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing...
User name is set to cdn
Sudo is disabled.
ssh-keygen: generating new host keys: DSA
User/password ssh access is disabled.
Public key from env variable added
chown: changing ownership of '/config/ssh_host_keys/ssh_host_rsa_key.pub': Read-only file system
chown: changing ownership of '/config/ssh_host_keys/ssh_host_ed25519_key.pub': Read-only file system
chown: changing ownership of '/config/ssh_host_keys/ssh_host_ecdsa_key.pub': Read-only file system
chown: changing ownership of '/config/ssh_host_keys/ssh_host_ed25519_key': Read-only file system
chown: changing ownership of '/config/ssh_host_keys/ssh_host_rsa_key': Read-only file system
chown: changing ownership of '/config/ssh_host_keys/ssh_host_ecdsa_key': Read-only file system
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by aptalca** [comment]
We don't support mapping in individual files like that. The host keys are in the `/config` folder which is meant to be persistent.

**Comment by Archelyst** [comment]
I can accept that, although this makes it quite cumbersome if not impossible to use the container in a cluster. Well, could you still tell me, why that is? I mean, it works as long as I only specify two of the three. The files are there, all looks the same as when not mapping the files.

**Comment by aptalca** [comment]
> Well, could you still tell me, why that is?

Because our init logic is designed around having a config folder mapped, not individual files underneath it

**Comment by Archelyst** [comment]
I managed to fix it. It works as expected. The key files were missing a new line at the end. Sorry to bother you.
