### ISSUE TITLE
consider non-interactive key generation for testing purposes

### ISSUE THREAD

**Issue by bukowa** [linuxserver/docker-openssh-server#62]
## Desired Behavior
I think it would be a great addition to (optionally) start this container ready to serve SSH with generated keys.
Useful in testing where keys and their lifetime doesn't really matter.

Maybe new environment variable that, if set, generates ssh keys via [keygen.sh](https://github.com/linuxserver/docker-openssh-server/blob/master/root/keygen.sh) and stores them by default in `~/.ssh/id_rsa` ?

**Comment by drizuid** [comment]
We welcome PRs

**Comment by drizuid** [comment]
We have no plans to implement this at this time.
