### ISSUE TITLE
Ability to forward a port with the -R (reverse) option

### ISSUE THREAD

**Issue by Astroamadeus** [linuxserver/docker-openssh-server#67]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

It would be nice to allow port forwarding in order to use the -R (reverse) option, for example in order to setup a reverse SSH tunnel through a dedicated and isolated docker container instead of through your main system.

## Current Behavior

Currently, commands like:

`ssh -R 192.168.1.1:2223:localhost:22 -p 2222 user@192.168.1.1`
(where the docker-openssh-server is running on 192.168.1.1)

return the following error:

`Warning: remote port forwarding failed for listen port 2223`

## Alternatives Considered

I have not found alternative options so far.

**Comment by daniel-falk** [comment]
I have the same issue/need.

It does seem like if the user has the capability to bind to ports, e.g. this works:
```bash
> ssh linuxserver.io@127.0.0.1 -p 2222 -i id-file nc -l 2000
```

As can be seen:
```bash
> ssh linuxserver.io@127.0.0.1 -p 2222 -i id-file netstat -tulpan
Active Internet connections (servers and established)
netstat: showing only processes with your user ID
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN      169/sshd.pam -D -e 
tcp        0      0 0.0.0.0:2000            0.0.0.0:*               LISTEN      201/nc
tcp        0      0 0.0.0.0:2000            0.0.0.0:*               LISTEN      197/nc
tcp        0      0 172.17.0.3:2222         172.17.0.1:52280        ESTABLISHED 202/sshd.pam: linux
tcp        0      0 172.17.0.3:2222         172.17.0.1:53282        ESTABLISHED 198/sshd.pam: linux
tcp        0      0 :::2222                 :::*                    LISTEN      169/sshd.pam -D -e
```

But remote port forwarding fails to listen to the same port:
```bash
> ssh linuxserver.io@127.0.0.1 -p 2222 -i id-file -R 2000:127.0.0.1:80 -N
Warning: remote port forwarding failed for listen port 2000
```

**Comment by Astroamadeus** [comment]
As a matter of fact I just found out that a mod exists (made by linuxserver.io) to cover exactly my request: [https://github.com/linuxserver/docker-mods/tree/openssh-server-ssh-tunnel](https://github.com/linuxserver/docker-mods/tree/openssh-server-ssh-tunnel)

I will check it and revert any issue (if any) in the dedicated section of this mod instead.

With regards,
