### ISSUE TITLE
Running in Azure Container Instance is broken due to init use

### ISSUE THREAD

**Issue by abaymar** [linuxserver/docker-openssh-server#68]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
ACI container should start and run

## Current Behavior
ACI container fails on start with _"s6-overlay-suexec: fatal: can only run as pid 1"_ message. 

## Steps to Reproduce

1. Describe a JSON with a container based off linuxserver/openssh-server:latest in Azure Container Instance
2. Create the ACI instance with  "restartPolicy":"Never" to see the log message.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by aptalca** [comment]
It's an issue with Azure, not the container, as it tries to hijack the init inside the container
