### ISSUE TITLE
[FEAT] Healthcheck for dockerfile

### ISSUE THREAD

**Issue by adamwoolhether** [linuxserver/docker-openssh-server#71]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Everything is perfect, just needs a HEALTHCHECK in the dockerfile to report when the ssh server is up and running.

### Reason for change

The container runs and State via `docker inspect` is "Running" before the SSH server actually initiates. This means there's no way to accurately tell when the container is _truly_ ready to serve ssh connections.

### Proposed code change

Add a HEALTHCHECK in the docker file.

**Comment by Roxedus** [comment]
As Organization policy we do not provide a healthchek. You are free to set your own healthcheck on deployment.
