### ISSUE TITLE
[BUG] Unable to start server on kubernetes using shareProcessNamespace with another container

### ISSUE THREAD

**Issue by rajan123456** [linuxserver/docker-openssh-server#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to run the openssh-server as a sidecar in a kubernetes pod using the shareProcessNamespace feature of kubernetes to share pid namespace between 2 containers. On doing this, the openssh-server crashes with the below log line:

```
s6-overlay-suexec: fatal: can only run as pid 1
```

I would like to have the ability to run the openssh-server without it requiring to run as pid 1

### Steps To Reproduce

NA

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
NA
```

### Container logs

```bash
s6-overlay-suexec: fatal: can only run as pid 1
```

**Comment by Roxedus** [comment]
The init system we use in our containers set this requirement, this is not a bug, as it needs to be PID 1 to work properly.
