### ISSUE TITLE
[FEAT] Add another versioning support

### ISSUE THREAD

**Issue by zewelor** [linuxserver/docker-openssh-server#89]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I think it would be good to add new versioning docker tag support, like: "9.7_p1-r3"

### Reason for change

Currently there is tag called "version-" but its not supported by renovate bot by default. Other images seems to have this kind of versioning scheme:

https://github.com/linuxserver/docker-healthchecks/pkgs/container/healthchecks ( 3.4.20240701 )
https://github.com/linuxserver/docker-mariadb/pkgs/container/mariadb ( 10.11.8 )

**Comment by aptalca** [comment]
https://www.linuxserver.io/blog/docker-tags-so-many-tags-so-little-time#4-pseudo-semver-tag-dynamic

**Comment by Roxedus** [comment]
The upstream version is not something we can parse safely to anything but `9.7_p1-r3` https://pkgs.alpinelinux.org/packages?name=*openssh-server-pam*&branch=v3.20 thus the current tagging scheme.

**Comment by zewelor** [comment]
Hi

thanks for quick response. Maybe it would be good to have tag for example "9.7_p1-r3" as alternative to current "version-9.7_p1-r3" ?

**Comment by Roxedus** [comment]
It would not. configure renovate properly against our tagging if you want to use it.

**Comment by aptalca** [comment]
3rd sentence from my link above:
`Utilizes logic to determine if upstream is using SemVer, and if determined not, this tag is not pushed`

**Comment by mbrodala** [comment]
Here is what we use now in our `renovate.json` BTW:

```json
  "packageRules": [
    {
      "matchPackageNames": ["ghcr.io/linuxserver/openssh-server"],
      "versioning": "regex:^(?<major>\\d+)\\.(?<minor>\\d+)_p(?<patch>\\d+)-(?<build>r\\d)-(?<revision>.+)$"
    }
  ]
```

Maybe not 100% correct but at least Renovate now suggests updates.

**Comment by zewelor** [comment]
Thanks for sharing ! I've wanted to use version- tag and i ended up with something similar in the end:

```
    {
      matchPackageNames: [
        "ghcr.io/linuxserver/openssh-server"
      ],
      versioning: "regex:^version-(?<major>\\d+)\\.(?<minor>\\d+)_p(?<patch>\\d+)-r(?<build>\\d+)$"
    },
```
