### ISSUE TITLE
[FEAT] LISTEN_PORT in documentation

### ISSUE THREAD

**Issue by orthlus** [linuxserver/docker-openssh-server#91]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add in documentation info about environment variable `LISTEN_PORT`

### Reason for change

In documentation not found info about environment variable `LISTEN_PORT`

**Comment by aptalca** [comment]
It's intentionally undocumented.

**Comment by orthlus** [comment]
> It's intentionally undocumented.

why?

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/docker-openssh-server/issues/30#issuecomment-1538129057
